version: '3.8'
services:
  web:
    build: .
    command: python /postgres_dj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/postgres_dj
    ports:
      - 8000:8000

  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"